# Generated by Django 4.2.11 on 2024-05-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_name_alter_recipe_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
