# Generated by Django 4.2.11 on 2024-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_quantity_ingredientinrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe_images', verbose_name='Картинка рецепта'),
        ),
    ]
