# Generated by Django 4.2.11 on 2024-05-09 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимый символ в имени пользователя', regex='^[\\w.@+-]+$')], verbose_name='Уникальный юзернейм'),
        ),
    ]
